# Generated by Django 3.2.8 on 2021-10-26 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('albumName', models.CharField(max_length=100)),
                ('albumArt', models.CharField(max_length=1000)),
                ('artistId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ArtistList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artistImage', models.CharField(max_length=1000)),
                ('artistName', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True)),
                ('artistGenre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SongsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songName', models.CharField(max_length=1000)),
                ('albumId', models.IntegerField()),
            ],
        ),
    ]
