# Generated by Django 3.2.8 on 2021-10-27 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unlabel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumlist',
            name='artistId',
        ),
        migrations.RemoveField(
            model_name='songslist',
            name='albumId',
        ),
        migrations.AddField(
            model_name='albumlist',
            name='artist',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='unlabel.artistlist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songslist',
            name='album',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='unlabel.albumlist'),
            preserve_default=False,
        ),
    ]
