# Generated by Django 3.2.8 on 2021-10-28 04:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('unlabel', '0003_albumlist_num_of_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumlist',
            name='published',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
