# Generated by Django 3.2.8 on 2021-11-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlabel', '0004_albumlist_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='songslist',
            name='lyrics',
            field=models.TextField(blank=True),
        ),
    ]
