# Generated by Django 3.2.8 on 2021-11-13 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unlabel', '0005_songslist_lyrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='regular', max_length=50)),
                ('artistImage', models.CharField(max_length=1000)),
                ('artistName', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True)),
                ('artistGenre', models.CharField(max_length=100)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
