# Generated by Django 3.2.8 on 2021-11-13 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unlabel', '0006_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumlist',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unlabel.artist'),
        ),
    ]
