# Generated by Django 3.2.8 on 2021-11-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlabel', '0009_delete_artistlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artistGenre',
            field=models.CharField(default='Trending', max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artistImage',
            field=models.CharField(default='artists/default.png', max_length=1000),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artistName',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
