# Generated by Django 3.2.8 on 2021-11-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlabel', '0010_auto_20211113_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artistName',
            field=models.CharField(default='defaultartistname', max_length=1000),
        ),
    ]
