# Generated by Django 3.2.8 on 2021-11-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlabel', '0013_action'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='artist',
            name='music_visibility',
            field=models.CharField(default='SM', max_length=2),
        ),
    ]
