# Generated by Django 3.2.8 on 2021-11-20 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlabel', '0014_auto_20211119_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
