# Generated by Django 3.2.8 on 2021-11-20 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unlabel', '0015_alter_comments_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-timestamp']},
        ),
    ]
